name: PR Analysis

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  sonar-analysis:
    # uses: dandsltd/o2c-devops/.github/workflows/sonar-analysis.yaml@develop
    uses: GITActionUdemy/sonar-analysis-action/.github/workflows/sonar-analysis.yaml@develop
    with:
      projectKey: o2c-report
      prAnalysisFeatureBranch: true
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      ENV_DECRYPT_KEY: ${{ secrets.ENV_DECRYPT_KEY }}